name: hotels-app

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev -- --host
    networks:
      - hotels-app
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - api
    networks:
      - hotels-app

  mongo:
    image: mongo:7.0.12
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    networks:
      - hotels-app

volumes:
  mongo_data:

networks:
  hotels-app:
    driver: bridge
